const { chromium } = require('./browser-tools/node_modules/playwright');
const { default: AxeBuilder } = require('./browser-tools/node_modules/@axe-core/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const out = path.join(__dirname, 'screenshots');
fs.mkdirSync(out, { recursive: true });
const report = { checks: [], accessibility: [], errors: [] };
const check = (name, condition) => { assert.ok(condition, name); report.checks.push(name); };
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: 'id-ID' });
    const page = await context.newPage();
    page.on('pageerror', error => report.errors.push(error.message));
    await page.goto('http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded' });
    await page.evaluate(() => document.fonts.ready);
    await page.waitForFunction(() => document.querySelector('video')?.readyState >= 2);
    await page.evaluate(() => { const v = document.querySelector('video'); v.pause(); v.currentTime = 8; });
    await delay(450);
    check('Hero keeps both original local video sources', await page.locator('video source').count() === 2);
    check('Transparent navbar at page top', await page.locator('.sk-nav--transparent').count() === 1);
    check('Light mode uses a white page background', await page.locator('.sk-home').evaluate(el => getComputedStyle(el).backgroundColor) === 'rgb(255, 255, 255)');
    const before = await page.locator('#services').evaluate(el => el.getBoundingClientRect().top + scrollY);
    await page.screenshot({ path: path.join(out, 'desktop-hero.png') });
    await page.evaluate(() => window.scrollTo(0, 630));
    await delay(450);
    check('Floating navbar appears after scroll', await page.locator('.sk-nav--floating').count() === 1);
    check('Floating navbar is fully rounded', await page.locator('.sk-nav-shell').evaluate(el => parseFloat(getComputedStyle(el).borderRadius)) >= 40);
    check('Navbar causes no content layout shift', Math.abs(before - await page.locator('#services').evaluate(el => el.getBoundingClientRect().top + scrollY)) < 1);
    const services = page.locator('.sk-nav-desktop button').filter({ hasText: 'Layanan' });
    await services.hover();
    await page.locator('#sk-services').waitFor({ state: 'visible' });
    check('Desktop submenu opens on hover', await services.getAttribute('aria-expanded') === 'true');
    const triggerBox = await services.boundingBox();
    await page.mouse.move(triggerBox.x + 20, triggerBox.y + triggerBox.height + 7);
    await delay(220);
    check('Pointer can cross the gap to submenu', await page.locator('#sk-services').isVisible());
    await page.locator('#sk-services a').first().hover();
    await page.screenshot({ path: path.join(out, 'desktop-floating-submenu.png') });
    await page.mouse.move(10, 500);
    await delay(220);
    check('Hover submenu closes after pointer leaves', await page.locator('#sk-services').count() === 0);
    await services.focus();
    await page.keyboard.press('Enter');
    await page.keyboard.press('Tab');
    check('Keyboard enters submenu links', await page.evaluate(() => document.activeElement?.getAttribute('href')) === '/layanan/penginapan');
    await page.keyboard.press('Escape');
    check('Escape closes submenu and returns focus', await page.locator('#sk-services').count() === 0 && await services.evaluate(el => el === document.activeElement));
    await page.locator('#sk-services-title').click();
    await page.locator('#destinations').scrollIntoViewIfNeeded();
    await page.evaluate(() => window.scrollTo(0, document.getElementById('destinations').offsetTop - 125));
    await delay(450);
    check('Four detailed destination cards restored', await page.locator('.sk-destination-card').count() === 4);
    check('Destination descriptions, prices and ratings are present', await page.locator('.sk-destination-price').count() === 4 && await page.locator('.sk-destination-rating').count() === 4);
    await page.screenshot({ path: path.join(out, 'desktop-destinations.png') });
    await page.evaluate(() => window.scrollTo(0, 0));
    await delay(450);
    await page.screenshot({ path: path.join(out, 'desktop-full.png'), fullPage: true });
    report.accessibility.push({ mode: 'desktop-light', violations: (await new AxeBuilder({ page }).include('.sk-home').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations });
    await page.getByRole('button', { name: 'Gunakan tema gelap' }).click();
    await page.evaluate(() => window.scrollTo(0, 750));
    await delay(450);
    report.accessibility.push({ mode: 'desktop-dark', violations: (await new AxeBuilder({ page }).include('.sk-home').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations });
    await page.screenshot({ path: path.join(out, 'desktop-dark.png') });

    const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1, locale: 'id-ID' });
    const mobile = await mobileContext.newPage();
    await mobile.goto('http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded' });
    await mobile.evaluate(() => document.fonts.ready);
    await mobile.waitForFunction(() => document.querySelector('video')?.readyState >= 2);
    await mobile.evaluate(() => { const v = document.querySelector('video'); v.pause(); v.currentTime = 8; });
    await delay(450);
    await mobile.screenshot({ path: path.join(out, 'mobile-hero.png') });
    check('Mobile has no horizontal overflow', await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await mobile.getByRole('button', { name: 'Buka navigasi' }).tap();
    await delay(450);
    check('Touch opens mobile navigation', await mobile.locator('#sk-mobile').isVisible());
    check('Open mobile menu has an opaque white background', await mobile.locator('.sk-nav-shell').evaluate(el => getComputedStyle(el).backgroundColor) === 'rgb(255, 255, 255)');
    check('Mobile exposes all three service routes', await mobile.locator('#sk-mobile a[href^="/layanan/"]').count() === 3);
    await mobile.screenshot({ path: path.join(out, 'mobile-menu.png') });
    await mobile.keyboard.press('Escape');
    check('Mobile Escape restores menu-button focus', await mobile.getByRole('button', { name: 'Buka navigasi' }).evaluate(el => el === document.activeElement));
    await mobile.evaluate(() => window.scrollTo(0, document.getElementById('destinations').offsetTop - 110));
    await delay(450);
    await mobile.screenshot({ path: path.join(out, 'mobile-destinations.png') });
    await mobile.evaluate(() => window.scrollTo(0, 0));
    await delay(450);
    await mobile.screenshot({ path: path.join(out, 'mobile-full.png'), fullPage: true });
    report.accessibility.push({ mode: 'mobile-light', violations: (await new AxeBuilder({ page: mobile }).include('.sk-home').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations });
    for (const width of [320, 375, 768, 1024, 1280]) {
      await page.setViewportSize({ width, height: 900 });
      check(`No horizontal overflow at ${width}px`, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    }
    const reduced = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    await reduced.goto('http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded' });
    check('Reduced motion disables autoplay', await reduced.locator('video').evaluate(el => el.paused));
    check('Reduced motion disables navbar transitions', await reduced.locator('.sk-nav-shell').evaluate(el => getComputedStyle(el).transitionDuration) === '0s');
    await reduced.getByRole('button', { name: 'Putar video' }).click();
    await delay(200);
    check('Video can still be played explicitly', await reduced.locator('video').evaluate(el => !el.paused));
    await reduced.getByRole('button', { name: 'Jeda video' }).click();
    check('Pause control works', await reduced.locator('video').evaluate(el => el.paused));
    await reduced.evaluate(() => localStorage.setItem('language', 'en'));
    await reduced.reload({ waitUntil: 'domcontentloaded' });
    check('English copy and destination data remain supported', await reduced.locator('#sk-hero-title').innerText().then(text => text.includes('A new story awaits')) && await reduced.locator('.sk-destination-card').first().innerText().then(text => text.includes('Iboih Beach')));
    for (const img of await reduced.locator('.sk-home img').all()) {
      await img.scrollIntoViewIfNeeded();
      await img.evaluate(el => el.decode());
    }
    check('Home images all load', await reduced.locator('.sk-home img').evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0)));
    check('No accessibility violations in the modified home and navbar', report.accessibility.every(result => result.violations.length === 0));
    fs.writeFileSync(path.join(__dirname, 'browser-review.json'), JSON.stringify(report, null, 2));
    console.log(JSON.stringify({ passed: report.checks.length, errors: report.errors, accessibility: report.accessibility.map(result => ({ mode: result.mode, violations: result.violations.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.map(n => n.target) })) })) }, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
